services:
  afkbot:
    build: .
    restart: unless-stopped
    environment:
      - MC_HOST=Amadeusjin.aternos.me
      - MC_PORT=30453
      - MC_USERNAME=AFKBot
    volumes:
      - ./auth:/app/auth
